### PR TITLE
change tech stack to vite and ts 

### PR DESCRIPTION
**Pull request by jacques-twizeyimana**
**What does this PR do?**

Changes the project tech stack to vite and typescript

**Description of Task to be completed?**

Migrates the existing codebase from webpack and babel to vite and typescript
Updates the dependencies and scripts in package.json
Fixes the type errors and lint issues
Refactors some components to use typescript features

### CODE REVIEW

**Comment by degide** [comment]
Good work @jacques-twizeyimana. Can you please merge (pull) from develop to include all latest changes like redux integration?

**Review by degide — CHANGES_REQUESTED** [review]
Please merge with develop for redux integration

**Review by degide — CHANGES_REQUESTED** [review]
good work

**Review by degide — APPROVED** [review]

**Review by MikeManzi — COMMENTED** [review]
Can you look into fixing the failing checks?

**Review by freddykaberuka — APPROVED** [review]

**Pull request merged**
